/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.Calculadora;
import Controller.CalculadoraImplementacao;
import Model.Trecho;
import Model.Trechos;
import Network.Servidor;
import java.net.MalformedURLException;
import java.rmi.Naming;
import java.rmi.NotBoundException;
import java.rmi.Remote;
import java.rmi.RemoteException;
import java.rmi.registry.LocateRegistry;
import java.util.Iterator;
import java.util.List;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;

/**
 *
 * @author Leandro Pereira Sampaio
 */
public class Interface extends javax.swing.JFrame {

    private Calculadora cal;
    private Calculadora calculadora;
    private int id;
    private Scanner leitura = new Scanner(System.in);
    private DefaultListModel dlm = new DefaultListModel();
    private DefaultListModel dlm2 = new DefaultListModel();

    /**
     * Creates new form Relogio
     */
    public Interface() {
        Servidor();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonMostrarTrechos = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        listaTrechos = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        listaReservas = new javax.swing.JList<>();
        buttonReservar = new javax.swing.JButton();
        buttonRemover = new javax.swing.JButton();
        buttonComprar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        buttonMostrarTrechos.setFont(new java.awt.Font("Trajan Pro", 1, 14)); // NOI18N
        buttonMostrarTrechos.setText("Mostrar Trechos");
        buttonMostrarTrechos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonMostrarTrechosActionPerformed(evt);
            }
        });

        jScrollPane1.setViewportView(listaTrechos);

        jScrollPane2.setViewportView(listaReservas);

        buttonReservar.setFont(new java.awt.Font("Trajan Pro", 1, 14)); // NOI18N
        buttonReservar.setText("Reservar => ");
        buttonReservar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonReservarActionPerformed(evt);
            }
        });

        buttonRemover.setFont(new java.awt.Font("Trajan Pro", 1, 14)); // NOI18N
        buttonRemover.setText("Remover");
        buttonRemover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonRemoverActionPerformed(evt);
            }
        });

        buttonComprar.setFont(new java.awt.Font("Trajan Pro", 1, 14)); // NOI18N
        buttonComprar.setText("Comprar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(buttonReservar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(buttonRemover, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(99, 99, 99)
                .addComponent(buttonMostrarTrechos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(buttonComprar)
                .addGap(105, 105, 105))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 430, Short.MAX_VALUE)
                            .addComponent(jScrollPane2)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(161, 161, 161)
                        .addComponent(buttonReservar)
                        .addGap(75, 75, 75)
                        .addComponent(buttonRemover)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonMostrarTrechos)
                    .addComponent(buttonComprar))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonMostrarTrechosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonMostrarTrechosActionPerformed
        mostrarTrechos();

    }//GEN-LAST:event_buttonMostrarTrechosActionPerformed

    private void buttonReservarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonReservarActionPerformed
        dlm2.addElement(listaTrechos.getSelectedValue()); //Pega o trecho escolhido na lista e adiciona na outra lista

        listaReservas.setModel(dlm2);
    }//GEN-LAST:event_buttonReservarActionPerformed

    private void buttonRemoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonRemoverActionPerformed
        dlm2.removeElement(listaReservas.getSelectedValue());

        listaReservas.setModel(dlm2);
    }//GEN-LAST:event_buttonRemoverActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interface().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonComprar;
    private javax.swing.JButton buttonMostrarTrechos;
    private javax.swing.JButton buttonRemover;
    private javax.swing.JButton buttonReservar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JList<String> listaReservas;
    private javax.swing.JList<String> listaTrechos;
    // End of variables declaration//GEN-END:variables

    public void Servidor() {
        try {
            System.out.println("Digite o id da Companhia Aérea:");
            id = leitura.nextInt();
            System.out.println("Digite a porta do servidor:");
            int porta = leitura.nextInt();

            LocateRegistry.createRegistry(porta);
            cal = new CalculadoraImplementacao();
            Naming.rebind("127.0.0.1/Calculadora" + id, (Remote) cal);

            leitura.nextLine();
            leitura.nextLine();
            fazerConexões();

            System.out.println("Servidor Remoto Iniciado...");
        } catch (RemoteException | MalformedURLException ex) {
            System.err.println("ERRO: " + ex.getMessage());
        }
    }

    /**
     * Fazer conexões com outras companhias aéreas
     *
     */
    public void fazerConexões() {
        try {
            for (int i = 1; i <= 3; i++) {
                if (i != id) {
                    calculadora = (Calculadora) Naming.lookup("127.0.0.1/Calculadora" + i);
                    /*
                    List trechos = calculadora.trechos(i);

                    Iterator it = trechos.iterator();
                    while(it.hasNext()){
                        Trecho trecho = (Trecho) it.next();
                        System.out.println("________________________________________________");
                        System.out.println("Origem: "+trecho.getOrigem());
                        System.out.println("Destino: "+trecho.getDestino());
                        System.out.println("________________________________________________");
                    }
                     */
                }
            }
        } catch (Exception ex) {
            System.err.println("ERRO: " + ex.getMessage());
        }
    }

    public void mostrarTrechos() {
        List trechos;
        try {
            for (int i = 1; i <= 3; i++) {
                if (i == id) {
                    Iterator it = cal.trechos(id).iterator();

                    while (it.hasNext()) {
                        Trecho trecho = (Trecho) it.next();
                        dlm.addElement("Origem: " + trecho.getOrigem() + " | " + "Destino: " + trecho.getDestino() + "  -  " + "Assentos: " + trecho.getQuantAssentos());
                    }

                } else if (i != id) {
                    calculadora = (Calculadora) Naming.lookup("127.0.0.1/Calculadora" + i);
                    trechos = calculadora.trechos(i);

                    Iterator it = trechos.iterator();
                    while (it.hasNext()) {
                        Trecho trecho = (Trecho) it.next();
                        dlm.addElement("Origem: " + trecho.getOrigem() + " | " + "Destino: " + trecho.getDestino() + " -  " + "Assentos: " + trecho.getQuantAssentos());
                    }
                }
            }
        } catch (RemoteException ex) {
            Logger.getLogger(Servidor.class.getName()).log(Level.SEVERE, null, ex);
        } catch (NotBoundException ex) {
            Logger.getLogger(Interface.class.getName()).log(Level.SEVERE, null, ex);
        } catch (MalformedURLException ex) {
            Logger.getLogger(Interface.class.getName()).log(Level.SEVERE, null, ex);
        }

        listaTrechos.setModel(dlm);
        //listaTrechos.getSelectedValue(); //Pega o trecho escolhido na lista
    }

}
